### ISSUE TITLE
Slack API for .NETCoreApp,Version=v1.1

### ISSUE THREAD

**Issue by juliepromact** [Inumedia/SlackAPI#105]
At present SlackApi is not compatible with .NETCoreApp,Version=v1.1.

**Comment by andymac4182** [comment]
New support has been added just hasn't been published to nuget yet. https://github.com/Inumedia/SlackAPI/pull/91

**Comment by juliepromact** [comment]
Yes. Noticed that. When will it be published to nuget ?

**Comment by gpailler** [comment]
Hello @juliepromact 
I don't know when @Inumedia will release a new version on Nuget but if you need .NetCore, you can use the prerelease version available on https://www.myget.org/feed/slackapi/package/nuget/SlackAPI
