### ISSUE TITLE
SlackClient.SearchFiles is not usable

### ISSUE THREAD

**Issue by mhgamework** [Inumedia/SlackAPI#106]
The SlackClient.SearchFiles returns a SearchResponseFiles, which does not publicly expose the "files" field. 
Furthermore, the SearchResponseFiles class has a private field "messages" which does not seem to make sense.

The SearchResponseFiles.cs file can be fixed by adding a public "files" field and remove the "messages field". I suggest this is merged into the project.
I currently use a workaround, where i copied the SlackClient.SearchFiles and have it use my own SearchResponseFiles class.

Corrected code:

```
[RequestPath("search.files")]
public class SearchResponseFiles : Response
{
    public string query;
    public SearchResponseFilesContainer files; // files, not messages AND public
}

public class SearchResponseFilesContainer
{
    /// <summary>
    /// Can be null if used in the context of search.all
    /// Please use paging.total instead.
    /// </summary>
    public int total;
    public PaginationInformation paging;
    public File[] matches;
}
```

**Comment by gpailler** [comment]
1.0.7 released
