### ISSUE TITLE
Not compatible with UAP

### ISSUE THREAD

**Issue by jamalmach** [Inumedia/SlackAPI#113]
On trying to add this package to a UWP project, the package restore fails. I attempted to add the package via console and the install failed with the following:

> Install-Package : SlackAPI 1.0.5.93 is not compatible with UAP,Version=v10.0.

Is this something that's going to be done/fixed?

**Comment by gpailler** [comment]
Could you try the prerelease Nuget package 1.0.6 available on MyGet (https://www.myget.org/feed/slackapi/package/nuget/SlackAPI)?
Version 1.0.6 should be compatible with netstandard1.3 (and UWP projects)

**Comment by jamalmach** [comment]
Thanks much. When is this getting brought to master? Any idea?

**Comment by gpailler** [comment]
It's already on master but it's not published on nuget yet.
Don't hesitate to report any odd behavior with the myget release so it can help us to decide when to publish on nuget.

**Comment by mediaexplorer74** [comment]
> On trying to add this package to a UWP project, the package restore fails. I attempted to add the package via console and the install failed with the following:
> 
> > Install-Package : SlackAPI 1.0.5.93 is not compatible with UAP,Version=v10.0.
> 
> Is this something that's going to be done/fixed?

Hi, from 2022. Where is your SlackUWP app (proto)? Your repos are empty.
