### ISSUE TITLE
SlackAPI fails logging into Google authenticated Slack accounts (need AuthMode "google")

### ISSUE THREAD

**Issue by christopherliu** [Inumedia/SlackAPI#116]
Hello!

We use Slack accounts authenticated by Google. Currently, SlackAPI includes two AuthModes -- normal and saml -- and it throws an error whenever authenticating into one of our bot accounts, which don't use either method.

I was able to get SlackAPI to work by making the following addition to TeamPreferences.cs:

```
        public enum AuthMode
        {
            normal,
            saml,
            google
        }
```

Thanks!

**Comment by gpailler** [comment]
1.0.7 released
