### ISSUE TITLE
missing websocket-sharp dependency?

### ISSUE THREAD

**Issue by vpopescu** [Inumedia/SlackAPI#126]
I was playing with the library and trying a client.Connect()... it was failing in that it was never completing the connect, but no error, just indefinite hang.

I tried calling the ConnectSOcket() call, and I saw a warning in my output file, that it cannot load "websocket-sharp". I then installed websocket-sharp:

PM> Install-Package WebSocketSharp -Pre

and then reverted my code to client.Connect(), and now it works.

Is it a known issue that we need to install WebsocketSharp separately? I installed 1.0.5.93 from nuget.

(Win10)

**Comment by gpailler** [comment]
I guess you installed SlackAPI.WebSocketSharp NuGet package (https://www.nuget.org/packages/SlackAPI.WebSocketSharp/) instead the official SlackAPI package.
SlackAPI doesn't rely on WebSocketSharp
