### ISSUE TITLE
Nuget package does not have "netstandard/.net core" support as stated in README.md

### ISSUE THREAD

**Issue by vonzepp** [Inumedia/SlackAPI#128]
https://www.nuget.org/packages/SlackAPI/
have only single framework target: .Net Framework 4.5
As I understand project already have "netstandard" build. Could you please update nuget package.

**Comment by razfriman** [comment]
This would help me tremendously

**Comment by razfriman** [comment]
Any updates on this?

**Comment by josephcooney** [comment]
There is a 1.0.6 build on the myget feed here https://www.myget.org/F/slackapi/api/v3/index.json that supports netstandard.

**Comment by gpailler** [comment]
Official 1.0.6 will be published soon on Nuget

**Comment by gpailler** [comment]
Duplicate of #123

**Comment by gpailler** [comment]
1.0.7 released
