### ISSUE TITLE
New Slack Users Cause KeyNotFoundException

### ISSUE THREAD

**Issue by DanRigby** [Inumedia/SlackAPI#15]
If a new Slack user registers and connects while the SlackClient is connected, a KeyNotFoundException is thrown due to the client (SlackClient.cs) being unable to locate the new user's id in it's UserLookup dictionary.

**Comment by nopjmp** [comment]
I believe I have a solution, but I need to make sure everything works before submitting a pull request. I'll mention the issue once I've completed testing. I've also gone ahead and implemented channel tracking and group tracking. However, I don't use the RPC API and only use the RTM WebSocket API.

**Comment by DanRigby** [comment]
@nopjmp I incorporated your changes into a custom build of SlackAPI and can confirm that they solve this issue for me.

**Comment by Inumedia** [comment]
I'll push a new nuget for this within a week or so. Currently on vacation ;)

**Comment by DanRigby** [comment]
@Inumedia: Sounds good!

**Comment by DanRigby** [comment]
@Inumedia Just a quick reminder about that new NuGet package. Thanks!

**Comment by Inumedia** [comment]
Aha, thanks for reminding me. I was planning on getting the NuGet package published once I got PR20 and PR18 merged in.

**Comment by DanRigby** [comment]
No problem!
