### ISSUE TITLE
PostEphemeralMessage returns user_not_in_channel

### ISSUE THREAD

**Issue by arise-project** [Inumedia/SlackAPI#150]
Hello Inumedia SlackAPI team.

I tested PostEphemeralMessage method in 1.0.7 nuget package, but it always respond with user_not_in_channel error, even I set channelId and targetuser properly. For example I port it with channelId=#general and targetuser=epirogov.

Thank you
Eugene

**Comment by gpailler** [comment]
I just added a unit test to validate the method and it seems it works fine. The `targetuser` property should contain the userId, not the username.

You can take a look on the UT here: https://github.com/Inumedia/SlackAPI/commit/63e92913cb12287f09d4a6e02088e8f17c60af04#diff-5715dd85793a0b9154cb39b2a411d70cR103

**Comment by arise-project** [comment]
Thank you. It works, only my user can see the message for now.
