### ISSUE TITLE
grant access for Auth.start Slack API method

### ISSUE THREAD

**Issue by Allauvdheenbasha** [Inumedia/SlackAPI#162]
I using your Slack API c# library, but I can’t make use of Auth.start method, it gave response as following 

_“{"ok":false,"error":"please_upgrade"}”._

Kindly guide me to use this API method.

**Comment by gpailler** [comment]
Could you post some code with context?
Did you checked the sample from the Wiki (https://github.com/Inumedia/SlackAPI/wiki/Complete-example-for-sending-a-message).

Does it work?

**Comment by Allauvdheenbasha** [comment]
send message method in slackclient is worked for me.

in slackclient class, i can't make use of SlackClient.StartAuth method.

when i execute SlackClient.StartAuth method like below.

 SlackClient.StartAuth((authStartResponse) =>
                {
                    var authresponse = authStartResponse;
                }, "Your mail id");

i have got response like this “{"ok":false,"error":"please_upgrade"}”.

**Comment by gpailler** [comment]
Well, the StartAuth method was marked Obsolete in SlackAPI code and is now probably removed on Slack side:
https://github.com/Inumedia/SlackAPI/blob/56e5471f4337850f40e07f75818cc703546484a0/SlackAPI/SlackClientHelpers.cs#L20

You should use the OAuth2 auth instead

**Comment by Allauvdheenbasha** [comment]
i cant use with FindTeam method in slackclient class. i passed valid workspace domain url to this method. 

it returns

{"ok":false,"error":"team_not_found"} 

kindly get me this one.

**Comment by gpailler** [comment]
Could you paste a repro code (you can hide the exact workspace name if you want)?

**Comment by Inumedia** [comment]
Closing as original issue refers to a deprecated API
