### ISSUE TITLE
StartAuth returns "please_upgrade"

### ISSUE THREAD

**Issue by mbrit** [Inumedia/SlackAPI#17]
This implies the auth method you've got as the first example in the wiki isn't supported?

**Comment by Inumedia** [comment]
Neat, the method I used was a hacked together / undocumented API. I'll investigate later today.

**Comment by mbrit** [comment]
I’d imagine they closed it — that’s a huge security hole for them if you can — unauthenticated — issue an arbitrary email address and get back a list of teams the user is subscribed to…  :-/

**Comment by Inumedia** [comment]
Yeah, I vaguely remember hearing them patch it, and I've noticed they stop supporting that on the web/official side of things.

**Comment by Inumedia** [comment]
Hm, guess I never closed this issue. I added an obsolete tag to the method in e35f62.
