### ISSUE TITLE
Request.cs is not thread-safe

### ISSUE THREAD

**Issue by shadow-cs** [Inumedia/SlackAPI#189]
Usage of `Dictionary` in `Request.cs` may result in unexpected exceptions if used by multiple threads. Such as while handling multiple requests in ASP.NET Core or when TPL is used.

https://github.com/Inumedia/SlackAPI/blob/8d777c99232c443fab247d0cc2839d48442e6a9c/SlackAPI/Request.cs#L144

**Comment by Inumedia** [comment]
Hi,

I think I see the problem with this. From the sound of it you could probably just go through all the types and populate the paths cache for a workaround, though I'm not sure how well that'd work if you use generic request objects.

**Comment by shadow-cs** [comment]
Already working on a fix ;-)
