### ISSUE TITLE
Missing functionality to open DM channel

### ISSUE THREAD

**Issue by Workshop2** [Inumedia/SlackAPI#19]
I am unable to find a way to open a DM channel (https://api.slack.com/methods/im.open) for my bot. 

If my bot isn't currently in a DM channel, I would like to open a channel then use it (or am I being silly and just can't see this function in the api?). 

Many thanks,
Simon

**Comment by Workshop2** [comment]
I have submitted a pull request to add this: https://github.com/Inumedia/SlackAPI/pull/20

**Comment by Inumedia** [comment]
#20 has been merged in. Forgot to close this.
