### ISSUE TITLE
Group.cs was not checked in.  Please fix build.

### ISSUE THREAD

**Issue by bmmathe** [Inumedia/SlackAPI#2]
I just pulled the code and there is a file called Group.cs which is not checked in but referenced by the project.  Please check the file in.  Thanks!

**Comment by Inumedia** [comment]
Group.cs is no longer needed, must have missed that when I checked it in. I'll check in a project file later tonight that doesn't reference it.

Thanks! :D

**Comment by Inumedia** [comment]
Pushed, shouldn't be in the project file anymore.
