### ISSUE TITLE
Where are the pins.* methods?

### ISSUE THREAD

**Issue by hrytskivr** [Inumedia/SlackAPI#201]
I'm trying to figure out how to pin/unpin message in Slack using this SlackAPI library and I can't find implementations of such methods. Where are they?

**Comment by Inumedia** [comment]
Those are not methods anyone has implemented in this library. My hunch is that it would be very easy to add support for them.

You're welcome to implement them and submit a PR for it

**Comment by hrytskivr** [comment]
Okay, thanks, I'll work on that and reference my pull request in this thread.
