### ISSUE TITLE
Invalid value for the type of the UserSelect element

### ISSUE THREAD

**Issue by jesdazrez** [Inumedia/SlackAPI#205]
I hit a bug while trying to send a group of blocks that included some UserSelect. Then I noticed that the UserSelect element was using an invalid type identifier.

![SlackAPIBug](https://user-images.githubusercontent.com/21959404/68650053-acba4100-04e9-11ea-8133-334e5f6b0ae4.png)

**Comment by Inumedia** [comment]
Fixed with 89e3fadfebf8914d1fb3cf5eb912f7c31750a7c2
