### ISSUE TITLE
Task/Async support

### ISSUE THREAD

**Issue by mbrit** [Inumedia/SlackAPI#21]
Hi,

Are you still after pull requests for this project?

Having been working with it today, I ideally need it to support the .NET 4.5 Task/async stuff, rather than this callback approach. I can work on your library, or I can create a parallel one?

Thoughts?

**Comment by Inumedia** [comment]
This was discussed before with another developer who wanted Task/async. I'm open to the idea of it and have no issue accepting pull requests that make the library easier to use.

**Comment by mbrit** [comment]
Hi -- I've now done this and have it in my fork. There's a separate SlackTaskClient class, and it's got *Async versions of all the original calls in it.

For some reason I can't create a pull requests for it -- I think it's saying the OAuth one I did before is still open?

**Comment by Workshop2** [comment]
I was just about to post a link to your pull request @mbrit -> https://github.com/Inumedia/SlackAPI/pull/18

**Comment by mbrit** [comment]
Ah, OK -- now that I look the existing request has both commits in it. I thought pull requests only did one commit, but obviously that'd be nuts so I'm on the same page now.

So yes, all I'm looking for is some feedback as to whether those two commits -- the OAuth implementation and the Task/async implementation -- can go into the main trunk.

**Comment by shepwalker** [comment]
Hey, I'm super interested in using the task functionality once its been merged. Is there anything blocking the PR?

**Comment by Inumedia** [comment]
Hi,

Sorry, not critical but I wanted to take some time to personally review and
test this before merging it in, but my free time has been pretty limited
lately.

**Comment by Inumedia** [comment]
Oh, I misread the email. There isn't currently a pull request for task/async functionality.

**Comment by shepwalker** [comment]
@Inumedia : it looks like @mbrit 's PR - #18 - included both OAuth and task/async. Totally understand that you're busy/do this in your free time - I super-appreciate that this is here in the first place. Thanks for all the great work!

**Comment by Inumedia** [comment]
#18 has now been merged, closing this ticket. :smile:

**Comment by Inumedia** [comment]
Again, sorry for the delay with merging this in. My personal life has been extremely busy lately.
