### ISSUE TITLE
SlackTaskClient is not allowing to Post with a valid OAuth Token (returns response "invalid_arguments")

### ISSUE THREAD

**Issue by DarienTGS** [Inumedia/SlackAPI#217]
This is my working code in C# that passes in a slackToken that I have defined in my environment variables.  It is used to connect to the SlackTaskClient just like shown here (https://github.com/Inumedia/SlackAPI/wiki/Examples) and it is returning the response invalid_arguments in the response message.  Perplexed as to why this is happening with a newly created OAuth token and the app has been added to the channel.

      private static async Task<PostMessageResponse> PostToSlack(string slackToken)
        {
            var slackClient = new SlackTaskClient(slackToken);
            var response = await slackClient.PostMessageAsync("#general", "test");
            return response;
        }

**Comment by Inumedia** [comment]
Hi, please try version 1.1.4 when it becomes available.

**Comment by DarienTGS** [comment]
Thank you I will.

We diagnosed the the problem you are sending as_user = false as part of the payload without using a guard statement so it always send and that is a deprecated argument.

Add a guard statement in your TaskClient for that check and it should be good to go again.

As for now we just created a basic HTTP client and are sending it manually using JSON but the SDK would be nice to use.

**Comment by Inumedia** [comment]
This should be fixed in 1.1.4, it should no longer send the `as_user = false` if it isn't supplied

**Comment by DarienTGS** [comment]
This has been fixed in 1.1.4.  Using the API documentation posting to a slack channel with an app now works with a valid OAuth token.
