### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by Andrew-EDSL** [Inumedia/SlackAPI#218]
The HTTPWebRequest by default seems to be using TLS 1 TLS1.1 which is no longer supported. 

Setting the security protocol in the same domain as the SlackTaskClient is created seems to solve the issue.

`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;`

**Comment by Inumedia** [comment]
FYI, this has been pushed to NuGet as version 1.1.6
