### ISSUE TITLE
slack User authentication API return Rate Limited

### ISSUE THREAD

**Issue by Aravind-E** [Inumedia/SlackAPI#219]
Hi, 

I have found below API in GitHub which is authenticating user in slack by User Id+password+team-ID combinations. But recently i have gotten "Rate-limited" issues at first call itself instead of continues call.
API :https://slack.com/api/auth.signin?user={0}&team={1}&password={2}&pretty=1.
 
I do need user token without installing slack app from workspace directory. worst case its works instead of regular.

**Comment by Inumedia** [comment]
afaik, logging in with username / password is deprecated by Slack's side. You can re-open this if you think this is a mistake
