### ISSUE TITLE
OnMessage callback on file upload

### ISSUE THREAD

**Issue by tommiv** [Inumedia/SlackAPI#24]
It looks like API notifies users about sent files with [file_share message subtype](https://api.slack.com/events/message/file_share). I suppose it's not implemented? I don't see `file` member in `NewMessage` class at all, and my OnMessage callback does not fire when I upload a picture.

**Comment by tommiv** [comment]
Hi there. I was really needed this, so I made a patch https://github.com/tommiv/SlackAPI/commit/c74278ec88b9851237af1379f48b7d7eda89ee52. I inherited new `FileShareMessage` from `NewMessage` and set up call to the same `OnMessageReceived` event. Don't know if you're ok with this two decisions. Let me know, if not, I'll change it.

**Comment by Inumedia** [comment]
Thanks tommiv, could you make a pull request for this?

**Comment by tommiv** [comment]
Sure, here is it https://github.com/Inumedia/SlackAPI/pull/31

**Comment by Inumedia** [comment]
Merged #31, closing this.
