### ISSUE TITLE
How to make SlackClient work with a corporate proxy?

### ISSUE THREAD

**Issue by dheeraj-pb** [Inumedia/SlackAPI#244]
We are behind a corporate proxy and I need to make the requests originating from SlackClient pass through a proxy. I was not able to find any option in the properties or methods within it.

**Comment by Inumedia** [comment]
Proxy support was added at 8dcb19c51cba4a6e4cde36b68e3f56d7a61cdaaa and should work in the latest version

**Comment by dheeraj-pb** [comment]
thank you. Closing the issue.
