### ISSUE TITLE
mono exception

### ISSUE THREAD

**Issue by 10der** [Inumedia/SlackAPI#25]
REPRO:

```javascript
        private static string slackKey = "xoxb-xxxxxxxxxxxxxxxxxxxxxxxx";
        static void Main(string[] args)
        {
            new SlackSocketClient(slackKey).
                Connect((r) => Console.WriteLine("Logged {0}", r.ok), () => { Console.WriteLine("Connected!"); });
            Console.ReadLine();
        }
```

Windows:
Connected!
Logged True

*Nix:
# mono Slack.exe

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at SlackAPI.RequestState`1[SlackAPI.LoginResponse].GotResponse (IAsyncResult result) [0x00000] in <filename unknown>:0
  at System.Net.WebAsyncResult.CB (System.Object unused) [0x00000] in <filename unknown>:0

**Comment by Inumedia** [comment]
Please consider re-generating your slackKey as it's now contained in the emails sent out to anyone subscribed to the issues on this repository.

**Comment by 10der** [comment]
thank you for respond!

**Comment by 10der** [comment]
Request.cs

internal void GotResponse(IAsyncResult result)

[Skipped]
```javascript
            Console.WriteLine("000000zzzzzzzzzzzzz");
            using (Stream responseReading = response.GetResponseStream())
            {
                Console.WriteLine("111111zzzzzzzzzzzzz");
                if (responseReading != null)
                {
                    using (StreamReader reader = new StreamReader(responseReading))
                    {
                        Console.WriteLine("22222222zzzzzzzzzzzzz");
                        string responseData = reader.ReadToEnd();
                        K responseObj = JsonConvert.DeserializeObject<K>(responseData, new JavascriptDateTimeConverter());
                        callback?.Invoke(responseObj);
                    }
                }
            }
```

 mono TestSlackAPI.exe
000000zzzzzzzzzzzzz

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at SlackAPI.RequestState`1[SlackAPI.LoginResponse].GotResponse (IAsyncResult result) [0x00000] in <filename unknown>:0
  at System.Net.WebAsyncResult.CB (System.Object unused) [0x00000] in <filename unknown>:0

so, exception occurred in using (Stream responseReading = response.GetResponseStream())
my guess - possible response is NULL.

here.
                //Anything that doesn't return error 200 throws an exception.  Sucks.  :l
                response = (HttpWebResponse)we.Response;
                //TODO: Handle timeouts, etc?

**Comment by 10der** [comment]
sorry:

   //Anything that doesn't return error 200 throws an exception.  Sucks.  :l
                response = (HttpWebResponse)we.Response;
                //TODO: Handle timeouts, etc?
>>>                Console.WriteLine(we.ToString());


look like crazy!


System.Net.WebException: Error getting response stream (Write: The authentication or decryption h            as failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed.             ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error co            de: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.RemoteValidation (Mono.Secu            rity.Protocol.Tls.ClientContext context, AlertDescription description) [0x00000] in <filename unk            nown>:0

**Comment by 10der** [comment]
thank you so much!

root@nas:/home/pi/C#/test# mono TestSlackAPI.exe
Connected!
Logged True

```
        public RequestState(HttpWebRequest requestData, Tuple<string, string>[] postParameters, Action<K> toCallback)
        {
    >>>>        ServicePointManager.ServerCertificateValidationCallback = (a, b, c, d) => { return true; };
            request = requestData;
            Post = postParameters;
            callback = toCallback;
        }
```

**Comment by Inumedia** [comment]
Ah, yeah the standard SSL/Mono cert problem. You can also use mozimports for this iirc.

http://stackoverflow.com/questions/3285489/mono-problems-with-cert-and-mozroots etc.

**Comment by Inumedia** [comment]
As a note, the code:
````
ServicePointManager.ServerCertificateValidationCallback = (a, b, c, d) => { return true; };
````
Ignores validation on all SSL certs regardless of if they're valid or not. This is a security hole for your application as a whole.

**Comment by 10der** [comment]
yes. its true. but I want to be sure what issue is here.
thank you so much, dev!

**Comment by Inumedia** [comment]
No worries, thanks for reporting this.
