### ISSUE TITLE
Connection timeout (Request.cs - GotResponse)

### ISSUE THREAD

**Issue by 10der** [Inumedia/SlackAPI#26]
issue still here :)

repro:
- turn off wifi or unplug RJ45 
- _client.Connect((r) =>
you got: {"Object reference not set to an instance of an object."}

hardcore repro:
```
            bool connecting = false;
            var watchdogTimer = new System.Timers.Timer(1000);
            watchdogTimer.Elapsed += (sender, arg) =>
            {
                if (!_client.IsConnected)
                {
                    if (connecting)
                    {
                    }
                    else
                    {
                        Console.WriteLine("Connect status: {0}", _client.IsConnected);
                        Console.WriteLine("Trying to connect");
                        connecting = true;
                        try
                        {
                            _client.Connect((r) =>
                            {
                                Console.WriteLine("Logged {0}", r.ok);
                                connecting = false;
                            },
                                () =>
                                {
                                    Console.WriteLine("Connected!");
                                });
                        }
                        catch (Exception ex)
                        {
                            connecting = false;
                        }
                    }
                }
                else
                {
                    // Console.WriteLine("Connect status: {0}", _client.IsConnected);
                }
            };
            watchdogTimer.Start();
            //..............................................
            Console.ReadLine();
```

1) run
2) Connect status: False
Trying to connect
Connected!
Logged True
3) turn off wifi or unplug RJ45 
4) please waiting, be patient.
5) Connect status: False
Trying to connect
6) +		$exception	{"Object reference not set to an instance of an object."}	System.NullReferenceException (
7) The thread 0x4e08 has exited with code 0 (0x0).
your console application is die!

Have a nice day, 
//Oleg

**Comment by Inumedia** [comment]
Hi Oleg,

That sounds like an issue with the SlackAPI library not automatically reconnecting for a RTM session. That functionality isn't implemented, is that something you wanted added and working?

**Comment by 10der** [comment]
Hi!

> not automatically reconnecting for a RTM session. 
no. I do not want "automatically reconnecting", I had best leave reconnecting mechanism in own bot, but core issues do not me control that (core exception). 
Ok, I'll fix that.

**Comment by Inumedia** [comment]
Sorry, is this an issue with reconnecting once the client has been disconnected?

**Comment by 10der** [comment]
who tf knows why. i can't remember. i fixed it locally. 
OK, i'll send this patch asap.

**Comment by Inumedia** [comment]
@10der haven't heard back from you, gonna close this for now. Let me know whenever you're ready to submit the pull request for this.
