### ISSUE TITLE
how to use slack api (conversationslist)

### ISSUE THREAD

**Issue by wooseong85** [Inumedia/SlackAPI#264]
Hello 
I need how to use slack api more example..
I try test conversations list in C# slack api .

ex)
in python api result list value =  {'ok': True, 'channels': [{'id': '123123123'}

but c# slack api result not found.
maybe test method wrong..

const string TOKEN = "my token"; 
var response1 = await slackClient.GetConversationsListAsync();

textBox1.Text = response1.ToString();  ==> SlackAPI.RPCMessages.ConversationsListResponse

how to get conveersations list result value like python?

thank you for your help..

**Comment by Inumedia** [comment]
I'm guessing you got this figured out?

**Comment by wooseong85** [comment]
I haven't solved it.
