### ISSUE TITLE
Config.json?

### ISSUE THREAD

**Issue by roschler** [Inumedia/SlackAPI#27]
I downloaded the source and attempted to built it.  I got a fatal error complaining that "config.json" could not be found.  Not surprising since it's listed in .gitignore:

https://github.com/Inumedia/SlackAPI/blob/46e6314c901c50ccaea062711f111ca8128c8c17/.gitignore

What should I do here to be able to build the solution?

**Comment by Workshop2** [comment]
Hey Roscher,

This is on purpose to ensure you don't commit slack keys to github. All you need to do is take a copy of the default config file, rename it and enter your details.

If you can think of a better way please let us know :smile:

**Comment by roschler** [comment]
Thanks, that explains it.  I usually expect to there be a "sample" file with the keys being set to YOUR_SLACK_API_KEY_HERE or some other label that makes it obvious to the user what is expected.  Preferably something that will cause a compiler error at the exact location the phony labels appears.
