### ISSUE TITLE
[SLACK 1.10] JoinDirectMessageChannelAsync is broken

### ISSUE THREAD

**Issue by liszto** [Inumedia/SlackAPI#271]
Hello,
we have an issue with `JoinDirectMessageChannelAsync` because it uses the parameter `user` instead of `users`

so currently we have to do 

`JoinDirectMessageChannelResponse jdmcResponse = await _slackTaskClient.APIRequestWithTokenAsync<JoinDirectMessageChannelResponse>(param);` to handle this.

**Comment by ramonsmits** [comment]
@liszto Tested with `master` and that works.

**Comment by bakester14** [comment]
Happy to make a PR for this, we had the same problem when we just updated to the newest version. This will break a lot of folks on upgrade.
