### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by bakester14** [Inumedia/SlackAPI#289]
The build is failing since #284 was merged. FYI @bbilginn

Going to delete the new test that was added to put the build back into a green state.

**Comment by bbilginn** [comment]
I don't know, does it matter? I copied another test and changed it but I forget to change the test method name, there are two of the same method. `SimpleMessageDelivery` 
And when I opened the pr, it passed tests, I am sorry to I did not try on my local.

**Comment by bakester14** [comment]
No need to apologize! 

Unfortunately, it does matter. If tests fail, appveyor doesn't run the packaging code, so none of the recently merged improvements are getting nugetized.

Compare the appveyor logs before and after your change to see what I mean.

Unfortunately found another issue blocking nuget from working as I was looking through the logs right now.
