### ISSUE TITLE
What should I put in the userAuthToken config field for a Bot integration?

### ISSUE THREAD

**Issue by roschler** [Inumedia/SlackAPI#29]
I am creating a new Bot integration for my team.  I already have an API token from Slack for my Bot and currently my config.json looks like this:

userAuthToken: ???
userAuthToken: <API Token>
testChannel: <name of test channel I created on Slack>
directMessageUser: <name of Bot>

What do I use for the userAuthToken field and are the other field assignments correct? (not the exact values of course, but what I'm using as the field value>.

Also, if  you have any tips on integrating the code with an ASP.NET/MVC web site, if that's possible, please let me know or point me to a document if one exists.

**Comment by roschler** [comment]
Anybody?  Really eager to try out SlackAPI.

**Comment by Inumedia** [comment]
Sorry, I thought this was answered. It sounds like you're trying to use the test interface which isn't the appropriate method to use this library.

**Comment by roschler** [comment]
I'm just trying to get started.  When I asked about config.json being missing and leading to a compile error on this thread:

https://github.com/Inumedia/SlackAPI/issues/27

"All you need to do is take a copy of the default config file, rename it and enter your details."

So I copied config.default.json to config.json and now I'm trying to put in the appropriate values.  Are you telling me "config.default.json" is not valid?  If so, where is the "default config file" mentioned by workshop2, so I can copy/rename and enter my details?

**Comment by roschler** [comment]
Still would like an answer to my question please.  Looking forward to working with SlackAPI.

**Comment by Workshop2** [comment]
I suspect you will need to generate an api key. Try the following link: https://api.slack.com/web

**Comment by roschler** [comment]
@Workshop2 - I got the API key/token a long time ago.  But the config.json file is also looking for a "user" token in addition to an API token and I have no idea what to put there.

**Comment by Workshop2** [comment]
This entire file is just about running integration (live) tests, and that part is testing the api works from user context and a bit context. They both have different security policies - might be worth reading up on that. You should also read and understand the integration tests before continuing: https://github.com/Inumedia/SlackAPI/blob/master/IntegrationTest/Connect.cs

**Comment by Inumedia** [comment]
@roschler Is this still a problem or were you able to get the library working successfully on your end?

**Comment by remms** [comment]
@roschler 
Just to clarify what those fields means:
userAuthToken: **To use slack as a user not a robot. For example, if you decided to code a custom UI. You shouldn't request username and password from the user, you should redirect to a page to request OAuth that will provide you a token. **
 botAuthToken:  **To access slack as a robot.**
 testChannel: **Channel to be used in the tests** 
 directMessageUser: **Same as testChannel, but for directMessage**

I'm just not sure if testChannel and directMessageUser are the names or the ids; If name, in the code you need to retrieve the id before sending the message.

**Comment by Inumedia** [comment]
Closing as we haven't heard back from @roschler
