### ISSUE TITLE
Nuget push failing due to missing environment variable

### ISSUE THREAD

**Issue by bakester14** [Inumedia/SlackAPI#291]
![image](https://user-images.githubusercontent.com/9834760/145471061-40557266-b28c-42fd-9727-fc2e508a9f74.png)
(from latest green build https://ci.appveyor.com/project/Inumedia/slackapi/builds/41811018)

Unfortunately this is blocking, and doubly unfortunately I'm not positive on what steps I can take to resolve this. @Inumedia do you still have the API token?

**Comment by Inumedia** [comment]
Fam chill, I know the build is broken, I still have access, I'll look into it later tonight.

I have a day job pls

I get emails for everything that happens in the repo, including the failing builds, I just didn't have time to investigate it yesterday.

**Comment by bakester14** [comment]
Thank you for everything! Sorry to bother you, I wasn't certain you were looking at this repo actively.
