### ISSUE TITLE
target dotnet core and not .net framework

### ISSUE THREAD

**Issue by orange-puff** [Inumedia/SlackAPI#296]
This package targets an old version of .net framework. Since it already targets .net standard 2.0, why not also target .netcore 

Addressed: https://github.com/Inumedia/SlackAPI/pull/297

**Comment by Inumedia** [comment]
From my understanding, netstandard should give the highest level of flexibility with where this library can be used.

While netcore is my preferred for starting new applications, I also understand that some people could be using this library inside of a legacy application that can't easily be upgraded.

**Comment by orange-puff** [comment]
Can we at least upgrade to net472?

**Comment by Inumedia** [comment]
I'm definitely more open to that, and don't see any issue with upgrading, but I'd also like to understand a bit better what's the push for the version change?

Is it just wanting the library to be on a newer version or is it being on an older version somehow a blocker for you?

**Comment by orange-puff** [comment]
I am consuming this package in a dotnet core 3.1 app. I receive intermittent errors due to not being able to find certain references to some of the Slack API code. When the dotnet build errors, a NU1701 warning is present complaining that Slack API is restored from .net framework, when the error is not present that warning is also not. 

I thought upgrading to .net 472, which is a more stable version of .net framework, might help. 

It is kind of a shot in the dark so perhaps it makes sense to just close this

**Comment by orange-puff** [comment]
This is not fleshed out
