### ISSUE TITLE
OnMessageReceived not called

### ISSUE THREAD

**Issue by demgod** [Inumedia/SlackAPI#3]
Relevant code listed below, the connection and hello events are called but not the OnMessageReceived event (Compiles fine, prints out Connection Received and Hello Received).

```C#
using SlackAPI;
using SlackAPI.WebSocketMessages;
using System;
using System.Net;
using System.Text;
using System.IO;

public SlackSocketClient gSlackClient;
const string SLACK_TOKEN = "MY_SLACK_TOKEN";

public void OnSlackConnected(LoginResponse lr)
{
    Log.Error("[SLACK MESSAGE] DEBUG: CONNECTION RECEIVED");
}

public void OnSlackHello()
{
    Log.Error("[SLACK MESSAGE] DEBUG: HELLO RECEIVED");
}

public void OnSlackMessageRecieved(Message m)
{
    Log.Error(string.Format("[SLACK MESSAGE] DEBUG: {0}", m.text));
}

public void Main()
{
    gSlackClient = new SlackSocketClient(SLACK_TOKEN);
    gSlackClient.OnHello += OnSlackHello;
    gSlackClient.OnMessageReceived += OnSlackMessageRecieved;
    gSlackClient.Connect(OnSlackConnected);
}
```

**Comment by Inumedia** [comment]
Fixed by eac567e6f78b02ccf742493b9a6703b81b1bf3fa

Thanks for letting me know about this :)

**Comment by chinswain** [comment]
Exactly the same issue using the same code (but via vb + linked dll) - latest build:
```
Dim gSlackClient = New SlackSocketClient("xxxxxx")
AddHandler gSlackClient.OnHello, AddressOf OnSlackHello
AddHandler gSlackClient.OnMessageReceived, AddressOf OnSlackMessageRecieved
gSlackClient.Connect(AddressOf OnSlackConnected)

Private Sub OnSlackHello()
     console.writeline("Hello") 'Fires
   End Sub

Private Sub OnSlackMessageRecieved(ByVal obj As NewMessage)
     Console.WriteLine(obj.text) 'Nothing
   End Sub

Private Sub OnSlackConnected(ByVal LoginResponse As LoginResponse)
     Console.WriteLine("connected") 'Fires
End Sub
```

**Comment by kenrachynski** [comment]
How are  you including the Slack API into your VB project? I'm using the NuGet package with VS2015 and am unable to duplicate  your issue. I.E. messages sent to my bot are showing up in my console window as expected.

**Comment by chinswain** [comment]
That's interesting, I'm building the DLL separately and adding it as a reference to the VB project. I'll try doing the same but to a C# project.

**Comment by kenrachynski** [comment]
I built sample apps in both VB and C# to verify. Maybe something in how you're building the DLL.

**Comment by Inumedia** [comment]
@chinswain I'll reopen it for now, could you email me some sample code and reproduction steps.

It sounds like it's as simple as:
* Chest out repo
* Build
* Copy compiled DLL
* Build VB.Net app against compiled DLL
* Run

But just in case I missed anything.

**Comment by chinswain** [comment]
Exactly that process- I've just tried the same using a C# project and it works fine (linking the compiled dll).
I'll try a vb project from scratch using the same code (converted) and DLL.

**Comment by Inumedia** [comment]
Thanks @chinswain !

**Comment by chinswain** [comment]
Interesting - It works within a VB app using the same code (converted), the only difference now is the failed test was on a difference machine, I'll have access to it this evening and test again, I'm guessing a firewall or sockets issue at this stage? This is via a bot so I can confirm messages are received fine via bots.

**Comment by Inumedia** [comment]
Welp. Not sure then. ¯\_(ツ)_/¯

**Comment by chinswain** [comment]
Well, I resolved this by removing the compiled c# dll from my project and adding it back (same dll) - worked from then on!

**Comment by Inumedia** [comment]
Awesome. Must have been that darn cosmic radiation. 😉
