### ISSUE TITLE
Reaction API support

### ISSUE THREAD

**Issue by WasabiFan** [Inumedia/SlackAPI#30]
According to [Slack's API docs](https://api.slack.com/methods), they have endpoints for getting/managing reactions on messages. Searching through this library's source code for the word "reaction", however, returns 0 results. Is there a technical reason that this isn't implemented, or is it just because no one has needed it?

**Comment by Inumedia** [comment]
It's not implemented simply because no one has needed it.

For your info, it's actually very easy to add it yourself if you need it immediately/urgently.

**Comment by WasabiFan** [comment]
No, it's not a problem. I'm just writing a quick script for my own use, so if I have a manual web request in the middle of my main method it won't be an issue :wink: If I get the extra time I might be able to implement it in the library itself and open a PR, but no promises.

**Comment by Inumedia** [comment]
You can always just make a new class for the reaction API stuff and then add a new method onto the appropriate slack interaction class (RTM/WebAPI)

iirc, there's also a manual API call with the interaction class.

**Comment by Inumedia** [comment]
@WasabiFan Can you confirm if this was fixed in #31 ?

**Comment by WasabiFan** [comment]
Yep, looks good. Thanks!
