### ISSUE TITLE
Create async versions of functions

### ISSUE THREAD

**Issue by danielrbradley** [Inumedia/SlackAPI#33]
Currently, the API design only allows asynchronicity via call-back actions. It would be really nice to have the option to have overloads of methods which returns a task which can be awaited. e.g.

```
public Task<ChannelListResponse> GetChannelList(bool ExcludeArchived = true)
```

This would be very useful when using the library as part of a server-side application.

**Comment by shepwalker** [comment]
Something beyond this: https://github.com/Inumedia/SlackAPI/blob/master/SlackTaskClient.cs ?

**Comment by danielrbradley** [comment]
Ah that'll do nicely :smile:

Had only found the `SlackClient` class [from the examples in the wiki](https://github.com/Inumedia/SlackAPI/wiki/Examples)
