### ISSUE TITLE
Receive Images from Slack

### ISSUE THREAD

**Issue by KillerSWAT** [Inumedia/SlackAPI#34]
We are currently able to receive messages, but not the images that come with them. Do you have an example for this use case?

**Comment by Inumedia** [comment]
I'm not 100% sure if the API for this, but you can probably just create a class for the API you receive from Slack for it and register the handler/callback for it.

**Comment by Inumedia** [comment]
Looking at this a little bit more, it sounds like the API on my side might be a outdated and might just not currently properly parse the image data. I'll look into this once I get a chance.

**Comment by Samichio** [comment]
I've got the same/a similar problem at the moment.
`
SlackSocketClient client = new SlackSocketClient(token);
client.GetFiles(x =>
{
        Console.WriteLine(x.files);
}, userID);
`
I get an error "user_is_bot". The "files.list" is not in the list of blocked permissions for Bot Users.

**Comment by Inumedia** [comment]
@Samichio That sounds like something you'd want to bring up to Slack's team. I have no control over that.

**Comment by pjc0247** [comment]
```cs
private static void OnMessageReceived(NewMessage obj) {
  if (obj is FileShareMessage) {
     var fm = (FileShareMessage)obj;
     if (fm.file.mimetype.StartsWith("image/")) {
        var downloadUrl = fm.file.url_private_download;
     }
  }
}
```
Remember that `url_private_download` is not a public link.
If you want to download the image, you must specify proper access token in `Authorization`  header.
(see https://api.slack.com/types/file , Authentication section)

**Comment by Inumedia** [comment]
Closing as @pjc0247 reminded me that this should be working and sounds like he has it working already. Also we haven't heard back from @KillerSWAT
