### ISSUE TITLE
Extensions.cs - ToProperTimeStamp extension issue

### ISSUE THREAD

**Issue by stpeteparadox** [Inumedia/SlackAPI#45]
Noticed that the GetFiles(Async) methods were not paying attention to the datetime values passed in to the to (ts_to) or from (ts_from) parameters.

Noticed in the Extensions.cs class in the ToProperTimeStamp static method that TrimEnd('0') does not remove the values after the decimal point in the string UTC timestamp. Tried testing the value that results from this method via the files.list method tester here https://api.slack.com/methods/files.list/test and it also failed to recognize that timestamp value.

Would it be possible to simply do 
string result = ((that.ToUniversalTime().Ticks - 621355968000000000m) / 10000000m).ToString("0");  which results in a timestamp with no decimal points, and that is recognized by the Slack API files.list method?

Thanks for this awesome implementation - really a time-saver.

**Comment by Inumedia** [comment]
I think there's a custom JSON converter for handling Dates which uses that extension. Wouldn't it make more sense to convert it to a long before sending it to Slack?
