### ISSUE TITLE
EmitPresence broken?

### ISSUE THREAD

**Issue by chinswain** [Inumedia/SlackAPI#58]
I'm getting unknown_method from SlackClient.EmitPresence

SlackClient.EmitPresence(AddressOf Presence, SlackAPI.Presence.active)

**Comment by Zaicon** [comment]
I've also encountered this issue when attempting to use this.

**Comment by Inumedia** [comment]
It might be deprecated. That was a method I found early on from reverse engineering the Android apk.

**Comment by chinswain** [comment]
You're right presense.set is depreciated - any change you could update for the the users.setPresence method?
https://api.slack.com/methods/presence.set

**Comment by chinswain** [comment]
My test bot is still showing as away - I think we might need to call users.setActive?

"it's possible to actively use a Slack client without causing any messages to be sent; in these situations the client can indicate activity has occurred by calling the API. Every Slack API method accepts an additional set_active argument. This can be used to indicate activity has occurred while performing the requested action.

If the user's activity generates no API calls then the client can periodically call users.setActive to let the Slack servers know about that activity."

https://api.slack.com/docs/presence
