### ISSUE TITLE
SlackAPI Connection unsuccessfull

### ISSUE THREAD

**Issue by Samichio** [Inumedia/SlackAPI#6]
I used the source, imported it into my project map and added the references in order to create a Bot User for Slack
I executed the following statement:
`SlackSocketClient client = new SlackSocketClient("TOKEN-TOKENTOKEN-TOKENTOKENTOKEN");
client.Connect((connected) =>
{
MessageBox.Show("Success!");
});`

No syntax errors. Unfortunately the connection is not successful.
![Values of client](http://puu.sh/ilc44/9c346e9d97.png)

Possibly an error on my side, but still. Thanks in advance!

**Comment by Inumedia** [comment]
Just to be sure, you are using a valid token when attempting to connect,
correct?

Also, could you try setting a break point on the message box show and see
if it ever gets hit? It might take a few seconds.

**Comment by Samichio** [comment]
I am using the token from here (im just gonna regenerate another token):
![ss 2015-06-11 at 10 00 55](https://cloud.githubusercontent.com/assets/12830412/8117001/7aa022be-1085-11e5-8cc4-55c38319e23e.png)
The message box show never gets hit, waited 10 minutes.

**Comment by Inumedia** [comment]
Odd, I'm seeing the issue in my tests. I'll work on getting this resolved asap.

**Comment by Inumedia** [comment]
As an update, I'll be looking deeper into this tonight, sorry for the delay just haven't had time.

**Comment by Inumedia** [comment]
I'm having trouble reproducing these problems. I've tried with both my own API token and a bot token, both times led to the callback being executed.

**Comment by Samichio** [comment]
Hey,

Sorry I took a day off of the grid yesterday.

Well thats great to hear, isnt it?
Would you upload your Project for me, so I can figure out what Im doing
wrong?

**Comment by Inumedia** [comment]
See the latest commit and look into the IntegrationTests project.

You can run the tests through Visual Studio's test explorer.

**Comment by Samichio** [comment]
I am starting to feel like an idiot...

I downloaded the project, added my token from the site already mentioned in this line:
`SlackSocketClient client = new SlackSocketClient("TOKEN");`
and ran the Tests.

Error at "Assert.IsTrue". Didn't return within a reasonable time. After 12 secounds.
I will try to run the tests without a firewall later this day, maybe it is somehow blocking it.

**Comment by Inumedia** [comment]
Where did you say you were located?

**Comment by Samichio** [comment]
Austria

**Comment by Inumedia** [comment]
Yeah, something's weird here. I could generally understand it taking longer than usual due to the distance, but 12 seconds is a bit extreme. I'm assuming you're not on dial up (56k) or something?

My connect test still comes in @ 1s and my bot @ ~600ms.

If you don't get any luck with your firewall let me know. We might have to setup some form of remote desktop to debug this. If you do get some luck, let me know, make a pull request containing any knowledge, or just post it to the wiki.

**Comment by Samichio** [comment]
10ms Ping, 80mbit down, 40mbit up
Still not working, even in an unprotected environment.
Timeout @ around 10-12s.

Do you want to try it with a remote desktop? You can write me on Twitter @Samichio

**Comment by dachibox** [comment]
Hi, is this bug solved?

greetings!

**Comment by Inumedia** [comment]
I believe this bug is currently resolved, even though @Samichio didn't close the issue.

**Comment by Samichio** [comment]
I am sorry, yes the issue is resolved. Visual Studio didnt automatically download the latest dependencies.(Newtonsoft.Json and WebSocket4)
