### ISSUE TITLE
Attachment is missing many properties

### ISSUE THREAD

**Issue by Franklin89** [Inumedia/SlackAPI#66]
The Attachment class is missing many properties that could be set while sending a message.

For example _image_url_

[Slack Api](https://api.slack.com/docs/message-attachments)

**Comment by pjc0247** [comment]
@Inumedia Hi, can you review [this](https://github.com/Inumedia/SlackAPI/pull/62) pull-request and merge it?
There's no `action` property either.

**Comment by gpailler** [comment]
PR #62 merged

**Comment by RyanMathewson** [comment]
Attachment needs a `callback_id`
[https://api.slack.com/docs/message-buttons](https://api.slack.com/docs/message-buttons)

**Comment by gpailler** [comment]
Fixed with Nuget package 1.0.5.93
