### ISSUE TITLE
NuGet Package Doesn't Add Project Reference

### ISSUE THREAD

**Issue by villainoustourist** [Inumedia/SlackAPI#7]
I get the dependancy references added without a problem - the SlackApi dll is downloaded to \packages\SlackAPI.1.0.1 - but no reference.  No a big deal to add manually, but a bit annoying to have to do so.

**Comment by Inumedia** [comment]
That's odd. Not really sure where this is bug is coming from. I'll take a look later tonight.

**Comment by distantcam** [comment]
Not sure how you build your package but the binaries are put in the root of the package and they should be put inside a lib folder instead.

**Comment by Inumedia** [comment]
Hrm. I found the specification which recommends putting binaries in a lib folder, I've pushed for version 1.0.2 which contains the libraries in a lib/ folder.

I'll put in different .net versions when I get the chance.

I referenced this page: https://docs.nuget.org/create/creating-and-publishing-a-package

**Comment by bootstraponline** [comment]
I think this can be closed now. Works fine for me using 1.0.5.1.
