### ISSUE TITLE
remove dependency from config.json to improve CI server integration

### ISSUE THREAD

**Issue by chintans** [Inumedia/SlackAPI#70]
config.json in IntegrationTests contains sensitive information. hence, It shouldn't be committed to the repository. This creates a problem for CI servers as they are unable to read config.json. A better solution would be to move all sensitive information to environment variables. This way it becomes CI friendly.

**Comment by gpailler** [comment]
We're working on it

**Comment by gpailler** [comment]
AppVeyor config with tests is handled in the scope of #71

**Comment by gpailler** [comment]
AppVeyor is configured on master
