### ISSUE TITLE
Remove WebSocket4Net library

### ISSUE THREAD

**Issue by Inumedia** [Inumedia/SlackAPI#8]
Remove WebSocket4Net library support from the real time messaging client

**Comment by nathanchere** [comment]
Not sure if it's related but whenever I take any kind of action I keep getting WebSocket4Net related errors. For example even just on a basic connection with the RTM client:

    var client = new SlackSocketClient(TOKEN);
    var wait = new EventWaitHandle(false, EventResetMode.ManualReset);
    client.Connect(x => wait.Set());
    result = wait.WaitOne(10000);

    An exception of type 'System.MissingMethodException' occurred in SlackAPI.dll but was not handled in user code

    Additional information: Method not found: 'Void WebSocket4Net.WebSocket..ctor(System.String, System.String, System.Collections.Generic.List`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.Collections.Generic.List`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.String, System.String, WebSocket4Net.WebSocketVersion)'.

**Comment by Inumedia** [comment]
That's odd. Try setting the reference to copy to local, let me know if that fixes anything.

**Comment by Inumedia** [comment]
@nathanchere Can you try out the latest code in the branch mentioned above ( 26f2fc3 ) and let me know if it resolves your MissingMethodException issues. :smile:

**Comment by nathanchere** [comment]
OK will do later today

**Comment by nathanchere** [comment]
The MissingMethodException has disappeared!

**Comment by nathanchere** [comment]
although when it comes to actually sending a message now it's giving null exception.

Example:

     client.Connect((o) => {
        Debug.WriteLine("RTM Start");
        wait.Set();
    });

    result = wait.WaitOne(10000);

    var user = client.Users.Single(x => x.name == "testbot");
    var dm = client.DirectMessages.Single(x => x.user == user.id);
    client.SendMessage(received => { Debug.WriteLine("Received: {0}", received.text); },
       dm.id,
       "testing");

dm, dm.id and client all have values. I'll dig around SlackSocketClient to try and see what's going on

**Comment by nathanchere** [comment]
OK so `underlyingSocket` is null when SendMessage is called. Maybe I'm just using it wrong but in my instance it was easily enough fixed in SlackSocketClient Connect by moving the `onConnected(s)` call after the `ConnectSocket(onSocketConnected` call.
