### ISSUE TITLE
Is there a way to send a prebuilt json message?

### ISSUE THREAD

**Issue by StingyJack** [Inumedia/SlackAPI#84]
I have an existing set of models for message, attachment, fields, etc that all serialize to Json very much like the ones contained in this project.  I would like to use the socket client and keep using these if possible, however if I call 

```
// .my custom message building stuff returns a message object with a .ToJson() function on it
// that would be the same as this var
var responseAsJson = "{"text":"You sent 'forcebot do stuff' which I do not understand","attachments":null}";

_SlackClient.SendMessage(OnSent, message.channel, responseAsJson);
```

this is the message that shows up in the channel.
>muhbotBOT [3:09 PM]  
>{"text":"You sent 'muhbot do stuff' which I do not understand","attachments":null}

Which is exactly the message i mean to send, however it seems to be getting escaped or rather double encoded. Is there a way to send prebuilt json messages that I am missing?

**Comment by nartamus** [comment]
Have you tried wrapping your braces in single quotes rather than double quotes?   '{"text".......

**Comment by StingyJack** [comment]
![image](https://cloud.githubusercontent.com/assets/15381181/21963247/5437322e-db05-11e6-8428-7fac95695c25.png)

**Comment by gpailler** [comment]
Sending already serialized json messages is not supported in SlackAPI.
But the following snippet should work in your case (we use a more "low-level" API method)

```csharp
var channel = client.Channels.Single(x => x.name == "general").id;
var responseAsJson = "{\"text\":\"You sent 'forcebot do stuff' which I do not understand\",\"attachments\":null}";
var responseAsDictionary = JsonConvert.DeserializeObject<Dictionary<string, string>>(responseAsJson);

var parameters = responseAsDictionary
  .Select(x => new Tuple<string, string>(x.Key, x.Value))
  .ToList();
parameters.Add(new Tuple<string, string>("channel", channel);

PostMessageResponse actual = null;
this.slackClient.APIRequestWithToken(
  (Action<PostMessageResponse>)(response => actual = response),
  parameters.ToArray()
  );
