### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by bootstraponline** [Inumedia/SlackAPI#85]
It'd be nice to have [tagged releases](https://help.github.com/articles/creating-releases/) to track what ends up on NuGet.

**Comment by bootstraponline** [comment]
Also FYI I updated the [examples](https://github.com/Inumedia/SlackAPI/wiki/Examples) page to demonstrate how to correctly wait for the client to connect. The default example had a race condition where a message could be sent to a client that didn't finish connecting.

The nuget package doesn't include source so when I debugged this, Visual Studio wanted to know where the source code was for the binary. That's when I found out there are no tags for releases.

**Comment by gpailler** [comment]
@bootstraponline Thanks for the feedback. We will pay attention to add tags and releases
