### ISSUE TITLE
Publish Updated Nuget Package

### ISSUE THREAD

**Issue by johnkoerner** [Inumedia/SlackAPI#94]
The official nuget package is still on 1.0.5.1 (published 2016-07-13): https://www.nuget.org/packages/SlackAPI/1.0.5.1

There is a rogue package that someone published as 1.2.3 (published :  2017-02-07) https://www.nuget.org/packages/Clints_Slack_API_1.2.3/1.2.3/

An official updated package should be created that contains the updates since 1.0.5.1.

**Comment by phess-andculture** [comment]
+1!

**Comment by gpailler** [comment]
It's a shame this publisher "forgot" to post an issue like you did ;-). 
But I agree, we should push an update (probably with PR #89 on it)

After this first updat, we can probably apply #91. This PR adds CakeBuild support (and .Net core) and it can ease Nuget package deployment

**Comment by johnkoerner** [comment]
I was specifically looking for #90 in the nuget package.

**Comment by gpailler** [comment]
Fixed with Nuget package 1.0.5.93
