### ISSUE TITLE
Handling and responding to file uploads

### ISSUE THREAD

**Issue by jocamar** [Inumedia/SlackAPI#95]
Hi,

I've been trying to build a Slack bot that responds to file uploads, but I haven't been able to find a way to respond to those events, apart from constantly checking the list of files.

Is there some way to register a callback for those kinds of events?

**Comment by gpailler** [comment]
Hello @jocamar 

This callback is not builtin in SlackAPI but you can easily create a custom callback to handle this kind of message.

According the doc, I think you need to subscribe [file_shared](https://api.slack.com/events/file_shared) message. 
```csharp
SlackSocketClient client;

private void Init()
{
    // Init of SlackSocketClient
    [...]

    this.client.BindCallback<NewFileSharedMessage>(this.OnNewFileShared);
}

private void OnNewFileShared(NewFileSharedMessage message)
{
  this.client.GetFileInfo(x => Console.WriteLine(x.file.name), message.file_id);
}

[SlackSocketRouting("file_shared")]
public class NewFileSharedMessage : SlackSocketMessage
{
  public string file_id;
  public string user_id;
}
```
